// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           19
// Async Callback:                       1
// Total number of exported functions:  21

#![no_std]

// Configuration that works with rustc < 1.73.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    jex_sc_stablepool
    (
        init => init
        configurePlatformFeesReceiver => configure_platform_fees_receiver
        setSwapFee => set_swap_fee
        issueLpToken => issue_lp_token
        enableMintBurn => enable_mint_burn
        pause => pause
        resume => resume
        addLiquidity => add_liquidity
        removeLiquidity => remove_liquidity
        removeLiquidityOneToken => remove_liquidity_one_token
        swap => swap
        estimateAmountOut => estimate_amount_out
        estimateAddLiquidity => estimate_add_liquidity
        estimateRemoveLiquidity => estimate_remove_liquidity
        estimateRemoveLiquidityOneToken => estimate_remove_liquidity_one_token
        getAnalyticsForLastEpochs => get_analytics_for_last_epochs
        getFees => lp_fees
        getTradingVolume => trading_volume
        getVirtualPrice => get_virtual_price
        isPaused => is_paused
    )
}

multiversx_sc_wasm_adapter::async_callback! { jex_sc_stablepool }
