// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           11
// Async Callback:                       1
// Total number of exported functions:  13

#![no_std]

// Configuration that works with rustc < 1.73.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    jex_sc_stablepool
    (
        init => init
        setSwapFee => set_swap_fee
        issueLpToken => issue_lp_token
        enableMintBurn => enable_mint_burn
        addLiquidity => add_liquidity
        removeLiquidity => remove_liquidity
        swap => swap
        estimateAmountOut => estimate_amount_out
        estimateAddLiquidity => estimate_add_liquidity
        estimateRemoveLiquidity => estimate_remove_liquidity
        getVirtualPrice => get_virtual_price
        isPaused => is_paused
    )
}

multiversx_sc_wasm_adapter::async_callback! { jex_sc_stablepool }
