[package]
name = "underlying-price-source-mock-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.underlying-price-source-mock]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.53.2"
default-features = false
